
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

public enum ItemLimitType {
    /**
     * 未定义
     */
    NONE(0),
    /**
     * 不限制数量的产出来源（商店、烹饪合成等）
     */
    UNLIMITED(1),
    /**
     * GM指令
     */
    GM(2),
    /**
     * 常规任务奖励
     */
    QUEST(3),
    ;

    /**
     * 未定义
     */
    public static final int NONE_VALUE = 0;
    /**
     * 不限制数量的产出来源（商店、烹饪合成等）
     */
    public static final int UNLIMITED_VALUE = 1;
    /**
     * GM指令
     */
    public static final int GM_VALUE = 2;
    /**
     * 常规任务奖励
     */
    public static final int QUEST_VALUE = 3;

    private final int value;

    private ItemLimitType(int value){
        this.value = value;
    }

    public int getNumber() {
        return value;
    }

    public static ItemLimitType forNumber(int value) {
        switch(value) {
            case 0: return NONE;
            case 1: return UNLIMITED;
            case 2: return GM;
            case 3: return QUEST;
            default:
                throw new java.lang.IllegalArgumentException("invalid value " + value + " for ItemLimitType");
        }
    }
}

