
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

public enum ItemLimitRefreshType {
    /**
     * 未定义
     */
    NONE(0),
    /**
     * 每日刷新
     */
    DAILY(1),
    /**
     * 每月刷新
     */
    MONTHLY(2),
    /**
     * 不刷新
     */
    PERSISTENT(3),
    ;

    /**
     * 未定义
     */
    public static final int NONE_VALUE = 0;
    /**
     * 每日刷新
     */
    public static final int DAILY_VALUE = 1;
    /**
     * 每月刷新
     */
    public static final int MONTHLY_VALUE = 2;
    /**
     * 不刷新
     */
    public static final int PERSISTENT_VALUE = 3;

    private final int value;

    private ItemLimitRefreshType(int value){
        this.value = value;
    }

    public int getNumber() {
        return value;
    }

    public static ItemLimitRefreshType forNumber(int value) {
        switch(value) {
            case 0: return NONE;
            case 1: return DAILY;
            case 2: return MONTHLY;
            case 3: return PERSISTENT;
            default:
                throw new java.lang.IllegalArgumentException("invalid value " + value + " for ItemLimitRefreshType");
        }
    }
}

