
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class ItemMiscConfig extends AbstractBean {
    public ItemMiscConfig(JsonObject _buf) { 
        bagCapacity = _buf.get("bag_capacity").getAsInt();
    }

    public static ItemMiscConfig deserialize(JsonObject _buf) {
            return new cfg.item.ItemMiscConfig(_buf);
    }

    /**
     * 背包容量
     */
    public final int bagCapacity;

    public static final int __ID__ = 1016762140;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "bagCapacity:" + bagCapacity + ","
        + "}";
    }
}

