
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


/**
 * 产出限制
 */
public final class ItemLimit extends AbstractBean {
    public ItemLimit(JsonObject _buf) { 
        type = _buf.get("type").getAsInt();
        refreshType = _buf.get("refresh_type").getAsInt();
    }

    public static ItemLimit deserialize(JsonObject _buf) {
            return new cfg.item.ItemLimit(_buf);
    }

    public final int type;
    public final int refreshType;

    public static final int __ID__ = 29443885;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "type:" + type + ","
        + "refreshType:" + refreshType + ","
        + "}";
    }
}

