
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


/**
 * 道具
 */
public final class Item extends AbstractBean {
    public Item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        type = _buf.get("type").getAsInt();
        stackLimit = _buf.get("stack_limit").getAsInt();
        quality = _buf.get("quality").getAsInt();
        dropable = _buf.get("dropable").getAsBoolean();
    }

    public static Item deserialize(JsonObject _buf) {
            return new cfg.item.Item(_buf);
    }

    /**
     * 道具id
     */
    public final int id;
    public final String name;
    public final int type;
    public final int stackLimit;
    public final int quality;
    public final boolean dropable;

    public static final int __ID__ = 2107285806;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "type:" + type + ","
        + "stackLimit:" + stackLimit + ","
        + "quality:" + quality + ","
        + "dropable:" + dropable + ","
        + "}";
    }
}

