
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

public enum ItemType {
    /**
     * 虚拟道具
     */
    VIRTUAL(1),
    /**
     * 材料
     */
    MATERIAL(2),
    /**
     * 武器
     */
    WEAPON(3),
    ;

    /**
     * 虚拟道具
     */
    public static final int VIRTUAL_VALUE = 1;
    /**
     * 材料
     */
    public static final int MATERIAL_VALUE = 2;
    /**
     * 武器
     */
    public static final int WEAPON_VALUE = 3;

    private final int value;

    private ItemType(int value){
        this.value = value;
    }

    public int getNumber() {
        return value;
    }

    public static ItemType forNumber(int value) {
        switch(value) {
            case 1: return VIRTUAL;
            case 2: return MATERIAL;
            case 3: return WEAPON;
            default:
                throw new java.lang.IllegalArgumentException("invalid value " + value + " for ItemType");
        }
    }
}

