
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import luban.*;
import com.google.gson.JsonElement;


/**
 * 产出限制表
 */
public final class TbItemLimit {
    private final java.util.HashMap<Integer, cfg.item.ItemLimit> _dataMap;
    private final java.util.ArrayList<cfg.item.ItemLimit> _dataList;
    
    public TbItemLimit(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, cfg.item.ItemLimit>();
        _dataList = new java.util.ArrayList<cfg.item.ItemLimit>();
        
        for (com.google.gson.JsonElement _e_ : _buf.getAsJsonArray()) {
            cfg.item.ItemLimit _v;
            _v = cfg.item.ItemLimit.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.type, _v);
        }
    }

    public java.util.HashMap<Integer, cfg.item.ItemLimit> getDataMap() { return _dataMap; }
    public java.util.ArrayList<cfg.item.ItemLimit> getDataList() { return _dataList; }

    public cfg.item.ItemLimit get(int key) { return _dataMap.get(key); }

}
