server:
  port: 8080
  type: 4
spring:
  application:
    name: router.V1
  cloud:
    config:
      enabled:  false
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true


discovery:
  endpoints:
   - http://localhost:2379
   - http://localhost:2379
  watch-servers:
    - service-name-prefix: game.V1
    - service-name-prefix: team.V1

redis:
  url: "redis://172.18.2.101:6379/0"

netty:
  server:
    SO_SNDBUF: 16777216
    SO_RCVBUF: 16777216
    WATER_MARK: 16777216