
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

public enum CoinType {
    /**
     * 钻石
     */
    DIAMOND(1),
    /**
     * 金币
     */
    GOLD(2),
    /**
     * 银币
     */
    SILVER(4),
    ;

    /**
     * 钻石
     */
    public static final int DIAMOND_VALUE = 1;
    /**
     * 金币
     */
    public static final int GOLD_VALUE = 2;
    /**
     * 银币
     */
    public static final int SILVER_VALUE = 4;

    private final int value;

    private CoinType(int value){
        this.value = value;
    }

    public int getNumber() {
        return value;
    }

    public static CoinType forNumber(int value) {
        switch(value) {
            case 1: return DIAMOND;
            case 2: return GOLD;
            case 4: return SILVER;
            default:
                throw new java.lang.IllegalArgumentException("invalid value " + value + " for CoinType");
        }
    }
}

