
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import luban.*;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;


public final class Item extends AbstractBean {
    public Item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
        stackLimit = _buf.get("stack_limit").getAsInt();
        quality = _buf.get("quality").getAsInt();
        dropable = _buf.get("dropable").getAsBoolean();
    }

    public static Item deserialize(JsonObject _buf) {
            return new cfg.Item(_buf);
    }

    /**
     * 道具编号
     */
    public final int id;
    /**
     * 道具类别
     */
    public final int type;
    /**
     * 最大叠加数量
     */
    public final int stackLimit;
    /**
     * 物品等级
     */
    public final int quality;
    /**
     * 可丢弃
     */
    public final boolean dropable;

    public static final int __ID__ = 2289459;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "stackLimit:" + stackLimit + ","
        + "quality:" + quality + ","
        + "dropable:" + dropable + ","
        + "}";
    }
}

