
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

public enum Quality {
    /**
     * 白
     */
    WHITE(1),
    /**
     * 绿
     */
    GREEN(2),
    /**
     * 蓝
     */
    BLUE(3),
    /**
     * 紫
     */
    PURPLE(4),
    /**
     * 橙
     */
    ORANGE(5),
    ;

    /**
     * 白
     */
    public static final int WHITE_VALUE = 1;
    /**
     * 绿
     */
    public static final int GREEN_VALUE = 2;
    /**
     * 蓝
     */
    public static final int BLUE_VALUE = 3;
    /**
     * 紫
     */
    public static final int PURPLE_VALUE = 4;
    /**
     * 橙
     */
    public static final int ORANGE_VALUE = 5;

    private final int value;

    private Quality(int value){
        this.value = value;
    }

    public int getNumber() {
        return value;
    }

    public static Quality forNumber(int value) {
        switch(value) {
            case 1: return WHITE;
            case 2: return GREEN;
            case 3: return BLUE;
            case 4: return PURPLE;
            case 5: return ORANGE;
            default:
                throw new java.lang.IllegalArgumentException("invalid value " + value + " for Quality");
        }
    }
}

