server:
  port: 4080
  type: 1
  tcp-port: 5080

spring:
  application:
    name: login.V1
  cloud:
    config:
      enabled:  false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true



discovery:
  endpoints:
    - http://localhost:2379
    - http://localhost:2379
  watch-servers:
    - service-name-prefix: gateway.V1
    - service-name-prefix: router.V1


mongo:
  addrs: localhost:27017;localhost:27017
  userName: admin
  password: admin
redis:
  url: "redis://172.18.2.101:6379/0"
