server:
  port: 4080
  type: 1
  group-id: 0
  tcp-port: 5080

spring:
  application:
    name: login.V1
  cloud:
    config:
      enabled: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true



discovery:
  endpoints:
    - http://172.18.2.101:2379
  watch-servers:
    - service-name-prefix: gateway.V1
    - service-name-prefix: router.V1


mongo:
  addrs: localhost:27017;localhost:27017
  userName: admin
  password: admin
redis:
  url: "redis://172.18.2.101:6379/0"

netty:
  client:
    workerCount: 4
    CONN_COUNT: 8
    SO_SNDBUF: 8388608
    SO_RCVBUF: 8388608
    WATER_MARK: 8388608