server:
  port: 7080
  type: 3
spring:
  application:
    name: game.V1
  cloud:
    config:
      enabled: false
  main:
    web-application-type: none
    allow-bean-definition-overriding: true
    allow-circular-references: true

#-------------------discovery ----------
discovery:
  endpoints:
    - http://localhost:2379
    - http://localhost:2379
  watch-servers:
    - service-name-prefix: router.V1

mongo:
  addrs: localhost:27017;localhost:27017
  userName: admin
  password: admin
  #redis://password@localhost:6379/0
redis:
  url: "redis://172.18.2.101:6379/0"

netty:
  server:
    workerCount: 4
    SO_SNDBUF: 16777216
    SO_RCVBUF: 16777216
    WATER_MARK: 16777216
  client:
    CONN_COUNT: 8
    SO_SNDBUF: 67108864
    SO_RCVBUF: 67108864
    WATER_MARK: 67108864